import type {
  Cluster,
  ClusterNode,
  Telemetry,
  Prediction,
  AppNotification,
  TwinCluster,
  TwinNode,
  TwinRoom,
  TwinSnapshot,
  User,
} from "@/types";

export const MOCK_USER: User = {
  id: 1,
  email: "admin@clusterdoctor.ai",
  full_name: "Dr. Cluster Admin",
  role: "ADMIN",
  is_active: true,
  is_superuser: true,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-07-25T10:00:00Z",
};

export const INITIAL_MOCK_CLUSTERS: Cluster[] = [
  {
    id: 1,
    name: "Production GPU Cluster Alpha",
    description: "Primary LLM Inference and Distributed Training Cluster (NVIDIA H100/RTX 4090)",
    location: "US-East (Datacenter A - Bay 4)",
    owner_id: 1,
    health_score: 94,
    status: "HEALTHY",
    created_at: "2026-01-10T08:00:00Z",
    updated_at: "2026-07-25T10:00:00Z",
  },
  {
    id: 2,
    name: "Kubernetes Edge Cluster Beta",
    description: "Low-latency microservices and gateway streaming workloads",
    location: "EU-Central (Datacenter B - Bay 12)",
    owner_id: 1,
    health_score: 68,
    status: "WARNING",
    created_at: "2026-02-15T09:30:00Z",
    updated_at: "2026-07-25T11:00:00Z",
  },
  {
    id: 3,
    name: "AI Fine-Tuning Cluster Gamma",
    description: "High-density compute cluster for multi-agent reinforcement learning",
    location: "US-West (Datacenter C - Bay 2)",
    owner_id: 1,
    health_score: 42,
    status: "CRITICAL",
    created_at: "2026-03-01T12:00:00Z",
    updated_at: "2026-07-25T11:15:00Z",
  },
  {
    id: 4,
    name: "Distributed Storage Delta",
    description: "Ceph & NVMe storage cluster carrying cluster state checkpoints",
    location: "AP-South (Datacenter D - Bay 1)",
    owner_id: 1,
    health_score: 99,
    status: "HEALTHY",
    created_at: "2026-04-10T14:00:00Z",
    updated_at: "2026-07-25T11:18:00Z",
  },
];

export const INITIAL_MOCK_NODES: ClusterNode[] = [
  {
    id: 101,
    hostname: "gpu-node-alpha-01",
    ip_address: "10.0.1.101",
    operating_system: "Ubuntu 24.04 LTS (Kernel 6.8)",
    cpu_model: "AMD EPYC 9654 96-Core Processor",
    cpu_cores: 96,
    gpu_model: "NVIDIA H100 SXM5 80GB",
    gpu_count: 8,
    ram_gb: 512,
    storage_gb: 4000,
    cluster_id: 1,
    cpu_usage: 45.2,
    gpu_usage: 78.5,
    memory_usage: 62.4,
    temperature: 61.5,
    power_consumption: 2850,
    status: "ONLINE",
    created_at: "2026-01-10T08:00:00Z",
    updated_at: "2026-07-25T11:19:00Z",
  },
  {
    id: 102,
    hostname: "gpu-node-alpha-02",
    ip_address: "10.0.1.102",
    operating_system: "Ubuntu 24.04 LTS (Kernel 6.8)",
    cpu_model: "AMD EPYC 9654 96-Core Processor",
    cpu_cores: 96,
    gpu_model: "NVIDIA H100 SXM5 80GB",
    gpu_count: 8,
    ram_gb: 512,
    storage_gb: 4000,
    cluster_id: 1,
    cpu_usage: 89.4,
    gpu_usage: 96.1,
    memory_usage: 91.8,
    temperature: 88.2,
    power_consumption: 3400,
    status: "ONLINE",
    created_at: "2026-01-10T08:00:00Z",
    updated_at: "2026-07-25T11:19:00Z",
  },
  {
    id: 103,
    hostname: "edge-node-beta-01",
    ip_address: "10.0.2.201",
    operating_system: "Debian 12 Bookworm",
    cpu_model: "Intel Xeon Platinum 8480+",
    cpu_cores: 56,
    gpu_model: "NVIDIA RTX 4090",
    gpu_count: 4,
    ram_gb: 256,
    storage_gb: 2000,
    cluster_id: 2,
    cpu_usage: 78.0,
    gpu_usage: 52.0,
    memory_usage: 84.5,
    temperature: 74.0,
    power_consumption: 1450,
    status: "ONLINE",
    created_at: "2026-02-15T09:30:00Z",
    updated_at: "2026-07-25T11:19:00Z",
  },
  {
    id: 104,
    hostname: "edge-node-beta-02",
    ip_address: "10.0.2.202",
    operating_system: "Debian 12 Bookworm",
    cpu_model: "Intel Xeon Platinum 8480+",
    cpu_cores: 56,
    gpu_model: "NVIDIA RTX 4090",
    gpu_count: 4,
    ram_gb: 256,
    storage_gb: 2000,
    cluster_id: 2,
    cpu_usage: 12.0,
    gpu_usage: 5.0,
    memory_usage: 22.0,
    temperature: 42.0,
    power_consumption: 450,
    status: "MAINTENANCE",
    created_at: "2026-02-15T09:30:00Z",
    updated_at: "2026-07-25T11:19:00Z",
  },
  {
    id: 105,
    hostname: "gamma-node-01",
    ip_address: "10.0.3.301",
    operating_system: "Ubuntu 22.04 Jammy",
    cpu_model: "AMD EPYC 7763 64-Core",
    cpu_cores: 64,
    gpu_model: "NVIDIA A100-SXM4-80GB",
    gpu_count: 4,
    ram_gb: 384,
    storage_gb: 3000,
    cluster_id: 3,
    cpu_usage: 98.6,
    gpu_usage: 99.8,
    memory_usage: 97.4,
    temperature: 94.8,
    power_consumption: 2900,
    status: "FAILED",
    created_at: "2026-03-01T12:00:00Z",
    updated_at: "2026-07-25T11:19:00Z",
  },
  {
    id: 106,
    hostname: "storage-node-delta-01",
    ip_address: "10.0.4.401",
    operating_system: "RHEL 9.4",
    cpu_model: "Intel Xeon Gold 6430",
    cpu_cores: 32,
    gpu_model: null,
    gpu_count: 0,
    ram_gb: 128,
    storage_gb: 16000,
    cluster_id: 4,
    cpu_usage: 24.5,
    gpu_usage: 0.0,
    memory_usage: 41.2,
    temperature: 48.0,
    power_consumption: 650,
    status: "ONLINE",
    created_at: "2026-04-10T14:00:00Z",
    updated_at: "2026-07-25T11:19:00Z",
  },
];

export const INITIAL_MOCK_PREDICTIONS: Prediction[] = [
  {
    id: 901,
    cluster_id: 1,
    node_id: 102,
    model_name: "ClusterDoctor-ThermalFailureNet-v3",
    prediction_type: "HARDWARE_THERMAL_THROTTLING",
    confidence: 0.94,
    risk_score: 89,
    probability: 0.94,
    predicted_label: "CRITICAL_THERMAL_RUNAWAY",
    recommendation: "Initiate auto-migration of 4 pod replicas from gpu-node-alpha-02 to edge-node-beta-01 immediately.",
    explanation: "VRM temperature junction reached 88.2°C with sustained 3400W power draw. High probability of thermal throttling within 4.2 minutes.",
    status: "PENDING",
    predicted_at: "2026-07-25T11:18:00Z",
    created_at: "2026-07-25T11:18:00Z",
    updated_at: "2026-07-25T11:18:00Z",
  },
  {
    id: 902,
    cluster_id: 3,
    node_id: 105,
    model_name: "ClusterDoctor-MemoryLeakPredictor-v2",
    prediction_type: "RAM_OOM_KILLED_RISK",
    confidence: 0.98,
    risk_score: 96,
    probability: 0.98,
    predicted_label: "OUT_OF_MEMORY_FATAL",
    recommendation: "Drain workload and isolate gamma-node-01. Target node storage-node-delta-01 suggested.",
    explanation: "Linear memory trajectory indicates kernel OOM panics in 90 seconds due to uncollected PyTorch CUDA tensors.",
    status: "PENDING",
    predicted_at: "2026-07-25T11:15:00Z",
    created_at: "2026-07-25T11:15:00Z",
    updated_at: "2026-07-25T11:15:00Z",
  },
  {
    id: 903,
    cluster_id: 2,
    node_id: 103,
    model_name: "ClusterDoctor-NetworkLatencyGuardian",
    prediction_type: "PACKET_LOSS_DEGRADATION",
    confidence: 0.76,
    risk_score: 62,
    probability: 0.76,
    predicted_label: "HIGH_LATENCY_SPIKE",
    recommendation: "Throttle non-essential batch sync jobs and monitor NIC rx_errors.",
    explanation: "Intermittent PCIe bus latency spikes detected on dual-port 100GbE Mellanox NIC.",
    status: "COMPLETED",
    predicted_at: "2026-07-25T10:45:00Z",
    created_at: "2026-07-25T10:45:00Z",
    updated_at: "2026-07-25T10:50:00Z",
  },
];

export const INITIAL_MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 501,
    title: "Critical Thermal Threshold Exceeded",
    message: "Node gpu-node-alpha-02 junction temperature is 88.2°C. AI Guardian recommends workload migration.",
    category: "prediction",
    threat_level: "CRITICAL",
    user_id: 1,
    cluster_id: 1,
    node_id: 102,
    prediction_id: 901,
    status: "UNREAD",
    read_at: null,
    created_at: "2026-07-25T11:18:10Z",
    updated_at: "2026-07-25T11:18:10Z",
  },
  {
    id: 502,
    title: "Node State Failed",
    message: "Node gamma-node-01 stopped heartbeating. OOM crash detected.",
    category: "system",
    threat_level: "HIGH",
    user_id: 1,
    cluster_id: 3,
    node_id: 105,
    prediction_id: 902,
    status: "UNREAD",
    read_at: null,
    created_at: "2026-07-25T11:15:30Z",
    updated_at: "2026-07-25T11:15:30Z",
  },
  {
    id: 503,
    title: "Auto-Healing Plan Recommended",
    message: "Safe Target selector identified edge-node-beta-01 (Capacity 78%) for incoming pods.",
    category: "self_healing",
    threat_level: "MEDIUM",
    user_id: 1,
    cluster_id: 2,
    node_id: 103,
    prediction_id: 903,
    status: "READ",
    read_at: "2026-07-25T11:00:00Z",
    created_at: "2026-07-25T10:46:00Z",
    updated_at: "2026-07-25T11:00:00Z",
  },
];

export function generateTelemetryHistory(nodeId: number, count = 20): Telemetry[] {
  const list: Telemetry[] = [];
  const now = Date.now();
  const node = INITIAL_MOCK_NODES.find((n) => n.id === nodeId) ?? INITIAL_MOCK_NODES[0];

  for (let i = count - 1; i >= 0; i--) {
    const timestamp = new Date(now - i * 30000).toISOString();
    const variance = (Math.random() - 0.5) * 8;
    const cpu = Math.min(100, Math.max(5, node.cpu_usage + variance));
    const temp = Math.min(105, Math.max(30, node.temperature + variance * 0.4));
    const ram = Math.min(100, Math.max(10, node.memory_usage + variance * 0.3));

    list.push({
      id: 1000 + nodeId * 50 + i,
      cluster_id: node.cluster_id,
      node_id: nodeId,
      cpu_usage: Number(cpu.toFixed(1)),
      cpu_temperature: Number(temp.toFixed(1)),
      cpu_frequency: 3800 + Math.floor(variance * 50),
      gpu_usage: Number(node.gpu_usage.toFixed(1)),
      gpu_temperature: Number((temp + 4).toFixed(1)),
      gpu_memory_usage: Number((ram * 0.9).toFixed(1)),
      gpu_power: Math.round(node.power_consumption * (cpu / 100)),
      ram_usage: Number(ram.toFixed(1)),
      swap_usage: 4.2,
      disk_usage: 48.5,
      disk_read_speed: Math.round(450 + Math.random() * 200),
      disk_write_speed: Math.round(320 + Math.random() * 150),
      network_in: Number((12.5 + Math.random() * 5).toFixed(2)),
      network_out: Number((18.2 + Math.random() * 8).toFixed(2)),
      latency: Number((1.2 + Math.random() * 0.8).toFixed(2)),
      packet_loss: temp > 85 ? 0.04 : 0.0,
      recorded_at: timestamp,
    });
  }

  return list;
}

const createTwinNode = (id: string, hostname: string, status: string, temp: number): TwinNode => ({
  node_id: id,
  status,
  cpu: 45,
  memory: 60,
  gpu: 75,
  temperature: temp,
  power: 2800,
  risk_score: temp > 85 ? 89 : 15,
  prediction: temp > 85 ? "Thermal Runaway" : "Normal",
  recommendation: temp > 85 ? "Migrate pods" : "None",
  updated_at: new Date().toISOString(),
});

export const MOCK_TWIN_ROOMS: TwinRoom[] = [
  {
    room_id: "room_alpha_main",
    name: "Primary Data Center Hall A",
    racks: [
      {
        rack_id: "rack_01",
        name: "Rack Alpha 1",
        x: -4,
        y: 0,
        z: -2,
        nodes: [
          createTwinNode("101", "gpu-node-alpha-01", "ONLINE", 61.5),
          createTwinNode("102", "gpu-node-alpha-02", "ONLINE", 88.2),
        ],
      },
      {
        rack_id: "rack_02",
        name: "Rack Beta 1",
        x: 0,
        y: 0,
        z: -2,
        nodes: [
          createTwinNode("103", "edge-node-beta-01", "ONLINE", 74.0),
          createTwinNode("104", "edge-node-beta-02", "MAINTENANCE", 42.0),
        ],
      },
      {
        rack_id: "rack_03",
        name: "Rack Gamma 1",
        x: 4,
        y: 0,
        z: -2,
        nodes: [
          createTwinNode("105", "gamma-node-01", "FAILED", 94.8),
          createTwinNode("106", "storage-node-delta-01", "ONLINE", 48.0),
        ],
      },
    ],
  },
];

export const MOCK_TWIN_CLUSTERS: TwinCluster[] = [
  {
    cluster_id: "1",
    health: 94,
    updated_at: new Date().toISOString(),
    nodes: [
      createTwinNode("101", "gpu-node-alpha-01", "ONLINE", 61.5),
      createTwinNode("102", "gpu-node-alpha-02", "ONLINE", 88.2),
    ],
  },
  {
    cluster_id: "2",
    health: 68,
    updated_at: new Date().toISOString(),
    nodes: [
      createTwinNode("103", "edge-node-beta-01", "ONLINE", 74.0),
      createTwinNode("104", "edge-node-beta-02", "MAINTENANCE", 42.0),
    ],
  },
];

export const CHATBOT_KNOWLEDGE_BASE: Record<string, string> = {
  health: "Current overall system health is **88%**. Cluster 1 and Cluster 4 are healthy, while Cluster 3 has 1 node in FAILED state due to an OOM panic.",
  thermal: "Node `gpu-node-alpha-02` (ID 102) is experiencing junction temperatures of **88.2°C** with 3400W power draw. AI Guardian recommends triggering auto-migration to `edge-node-beta-01`.",
  migrate: "To migrate workloads: Click **Recovery** or **Migration** in the navigation bar, select target node `edge-node-beta-01`, and initiate the AI Healing Pipeline.",
  predictions: "We have **2 active critical predictions**: Thermal Runaway on `gpu-node-alpha-02` (Risk: 89) and Out of Memory Panic on `gamma-node-01` (Risk: 96).",
  default: "I am **Cluster Doctor AI Copilot**. I can help you monitor cluster telemetry, diagnose hardware issues, run digital twin simulations, and orchestrate self-healing workloads.",
};
